### ISSUE TITLE
Bad signature for .simulate() callback

### ISSUE THREAD

**Issue by openhoat** [auth0/webtask-runtime#6]
In the simulate function example of the documentation, two arguments are specified for the callback :
```
Runtime.simulate(webtask, { secrets: { hello: 'world' }}, function (err, res) {
...
```

In fact there is no error provided, but only the response object so the signature should be :
```
Runtime.simulate(webtask, { secrets: { hello: 'world' }}, function (res) {
...
```

**Comment by ggoodman** [comment]
Hi @openhoat. You're absolutely right.
