### ISSUE TITLE
Remote Address is not available on the request object

### ISSUE THREAD

**Issue by ktsashes** [auth0/webtask-runtime#7]
The remote address that is requesting the webtask is not available via the `req` object passed in. The value is `undefined`, and the `x-forwarded-for` header points only to a private IP address. This makes doing things like location based webtasks that key off of that value not possible. At least, I was not able to find that remote address anywhere else in the object or context (unless I missed it).

Here's a quick code sample to demonstrate the problem:

```javascript
module.exports = function (context, req, res) {
  res.end(req.remoteAddress || 'Remote Address not available');
};
```

**Comment by ggoodman** [comment]
Hello @ktsashes, thanks for your interest. As you've observed, we don't have the proxy protocol wired up across the stack and the `x-forwarded-for` points to a private ip in our infrastructure. 

This isn't a feature for which we have had much demand, though I can appreciate how it could be useful for things like your weather icon (cool idea!).
